### ISSUE TITLE
ParseError: Unexpected token

### ISSUE THREAD

**Issue by idelsink** [coderdiaz/vue-status-indicator#1]
When I import the module using: 
```js
import StatusIndicator from 'vue-status-indicator';
```

I get the following error:

```text
<some path>/node_modules/vue-status-indica
tor/src/components/StatusIndicator.vue:1                                        
<template>                                                                      
^                                                                               
ParseError: Unexpected token
```

I think this has to do with the missing `lang="html"` attribute in the template element.

**Comment by idelsink** [comment]
Hm I tried it out, my PR and it seemed to work. However it's still failing. I think I had some caching issues. 
The problem I have that vueify doesn't run over the node_modules folder.

For example look at the following issue: https://github.com/vuejs/vueify/issues/214.

**Comment by coderdiaz** [comment]
@idelsink 
Interesting.. I'll review. Can you reply the issue in another repo, please?

**Comment by coderdiaz** [comment]
Working on it :)
