### ISSUE TITLE
How to make a pulsating indicator?

### ISSUE THREAD

**Issue by richardeakin** [coderdiaz/vue-status-indicator#10]
I've tried the obvious code:

```
    <status-indicator status="positive" pulse=true />
```

Could you please help me correct this? Also apologies if this was in the guide, I didn't see it.

**Comment by coderdiaz** [comment]
Hi @richardeakin, use only the pulse property:
```html
<status-indicator pulse />

<!-- or -->
<status-indicator :pulse="true" />
```
