### ISSUE TITLE
Error when using in vue project

### ISSUE THREAD

**Issue by JanLechowskiTheFirst** [coderdiaz/vue-status-indicator#6]
/home/j/projekt/C/confirmo/src/node_modules/vue-status-indicator/styles.css:1
(function (exports, require, module, __filename, __dirname) { :root {
                                                              ^

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at npmRequire (/home/j/projekt/C/confirmo/src/.meteor/local/build/programs/server/npm-require.js:133:10)
    at Module.useNode (packages/modules-runtime.js:664:18)
    at styles.css (packages/modules.js:347:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/home/j/.meteor/packages/modules/.0.13.0.60cbwj.yyusx++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at /home/j/projekt/C/confirmo/src/.meteor/local/build/programs/server/app/app.js:2844:8
    at HelloPageCustomer.vue (app/features/customer/HelloPageCustomer.vue:71:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /home/j/projekt/C/confirmo/src/.meteor/local/build/programs/server/app/app.js:3346:1
    at /home/j/projekt/C/confirmo/src/.meteor/local/build/programs/server/boot.js:419:36
Exited with code: 1
Your application is crashing. Waiting for file change.

Usage:
<template>
    <v-layout row wrap v-if="$subReady.policies && $subReady.cars">
        <v-flex fill-height xs12 s6>
            <v-card>
            <v-btn @click.native="navToNewReqest()"
                    color="pink"
                    dark
                    absolute
                    small
                    top
                    right
                    fab
            >
                <v-icon>add</v-icon>
            </v-btn>
            </v-card>

            <v-data-table
                :headers="headers"
                :items="allRequestsForCurrentUser"
                hide-actions
            >
                <template v-slot:items="props">
                <td >{{ props.item.policy.policyNumber }}</td>
                <td >{{ props.item.policy.car.car.regNumber }}</td>
                <td><status-indicator active pulse></status-indicator></td>
                <td >{{ props.item.policy.statusList[0].status.code}}</td>
                </template>
            </v-data-table>
        </v-flex>
    </v-layout>
</template>
<script>
import { Meteor } from 'meteor/meteor';
import {Policies} from '../policy/api/collections';
import {Cars} from '../policy/api/collections';  
import 'vue-status-indicator/styles.css'

    export default {
        name: "HelloPageCustomer",
        data () {
            return {
                headers: [
                { text: 'Nr polisy', value: 'policyNumber' },
                { text: 'Nr rejestracyjny', value: 'regNumber' },
                { text: 'Status', value: 'status' },
                ],
            }
        },
        methods:{
            navToNewReqest(){
                this.$router.replace("/addPolicy");
            }
        },
        meteor: {
            $subscribe: {
                policies: [],
                cars:[],
            },
            policyForUserName(){
                return Policies.find({"policy.userName" : "kingpin"});
            },
            allRequestsForCurrentUser(){
                var policy = this.policyForUserName;
                console.log("length:"+policy.length);
                for(var index = 0;index < policy.length;index++){
                var car =  Cars.findOne({_id : policy[index].policy.carRef});
                console.log(car.car.regNumber);
                policy[index].policy.car=car;
                }
                return policy; //obecny userName pobierane bedzie z sesji
                }
            }    
    }
</script>

<style lang="stylus" scoped>
</style>

**Comment by coderdiaz** [comment]
@JanLechowskiTheFirst Thanks for the feedback!

**Comment by coderdiaz** [comment]
Fixed in 44154e7 now use the latest version.
